SHOT-4030: SDV fix for collapsing a single layer
shotgunsoftware/tk-alias pull request #108
Opened 2022-05-17 15:07 UTC by staceyoue

* Remove the "collapse" action for individual layers, as it causes issues due to dependencies
* Add dependency "zero transforms" to "layer has single item" (geometry may be re-parented and affects the geometry if it has not had zero transform applied to it before hand)
* Update "delete empty sets" wording to clarify "selection sets"
* Add item action to individual layers to select their geometry for "layer has single item"

2022-05-18 18:59 UTC, rob-aitchison requested changes

2022-05-18 18:59 UTC, rob-aitchison commented on python/tk_alias/scene_data_validator.py
> +                                Layers can only have a single top-level object. If it contains multiple objects, they will be placed int oa single group.<br>
typo - into a :)

2022-05-18 20:25 UTC, rob-aitchison requested changes
@staceyoue did you mean to commit and push the init and engine file changes to this particular branch / PR?

2022-05-20 14:24 UTC, staceyoue commented
@rob-aitchison added another fix for a typo, and placement of periods and brackets

2022-05-20 18:11 UTC, rob-aitchison approved these changes
👍🏻

2022-05-20 18:47 UTC, merged