SG-34683 - Rebranding
shotgunsoftware/tk-alias pull request #183
Opened 2024-02-27 18:16 UTC by juanburgosautoglb

Change all the shotgrid/shotgun occurrences in the repository.

2024-02-28 19:57 UTC, julien-lang commented
I still find references to ShotGrid in startup.py:
```python
    # The name used to establish the Flow Production Tracking Alias Engine client with Alias
    TK_ALIAS_CLIENT_NAME = "shotgrid"
```

2024-02-28 22:15 UTC, staceyoue requested changes

2024-02-28 22:15 UTC, staceyoue commented on startup.py
> +    TK_ALIAS_CLIENT_NAME = "flow production tracking"
We can't have spaces in the client name
```suggestion
    TK_ALIAS_CLIENT_NAME = "flow-production-tracking"
```

2024-02-28 22:15 UTC, staceyoue commented on python/tk_alias/menu_generation.py
>              self.__menu_name = "al_shotgrid"
We need to keep `al_shotgrid` as is, because Alias has defined the menu for us using this name, for Alias < 2024.

2024-02-28 22:21 UTC, julien-lang approved these changes
LGTM!

2024-02-29 15:40 UTC, staceyoue commented on python/tk_alias/menu_generation.py
>              self.__menu_name = "al_shotgrid"
I don't see this change in the PR anymore?
```
        if self._version_check(engine.alias_version, "2024.0") >= 0:
            self.__menu_name = "ShotGrid"
            self.__menu_name = "Flow Production Tracking"
```
We want this rename, but keep the `al_shotgrid` and `al_shotgun` menu names for Alias < 2024

2024-02-29 15:43 UTC, staceyoue commented on python/tk_alias/menu_generation.py
>              self.__menu_name = "al_shotgrid"
Strangely I don't see this commit in the PR anymore. When I go to File changed (as well as I have checked out the branch), we still have
```
if self._version_check(engine.alias_version, "2024.0") >= 0:
    self.__menu_name = "ShotGrid"
```

2024-02-29 16:45 UTC, staceyoue submitted a review, later dismissed

2024-02-29 16:48 UTC, julien-lang approved these changes

2024-03-20 20:19 UTC, julien-lang approved these changes

2024-03-20 20:19 UTC, merged